#%{NOM:buyer} bought %{INT:quantity}  from %{NOM:seller} for %{PRICE:price} %{NOM:buyer_account} into %{NOM:seller_account} 
input
{
  file
  {
    path => "/home/kodstok/elk_eco/data_without_html.json"
    codec => json
    sincedb_path => "/dev/null"
    start_position => "beginning"
  }
}

filter
{
  json
  {
     source => "message"
  }

  date
  {
    match => ["Timestamp" , "UNIX"]
    target => "Timestamp_UNIX"
  }
}
filter 
{
  grok 
  {
    match => 
    { 
    "message" => ".*\"%{NOM:buyer} bought %{INT:quantity}  from %{NOM:seller} for %{PRICE:price} %{NOM:buyer_account} into %{NOM:seller_account}.*"
    }
    pattern_definitions =>
    {
      "NOM" => "[:alpha:0-9]*"
      "INT" => "[0-9]*"
      "PRICE" => "[0-9]*[.][0-9]*"
    }


  }
}

output{
    elasticsearch{
        hosts => "localhost:9200"
        index => "test"
    }
    stdout { codec => rubydebug }
}
